version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8080:80  # Accéder à WordPress via http://localhost:8080
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content 
    networks:
      - wordpress_network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Autoriser root sans mot de passe
      MYSQL_DATABASE: wordpress
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80  # Accéder à phpMyAdmin via http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_USER: root  # Utiliser root sans mot de passe
      PMA_PASSWORD: ""  
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
